name: Publish
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Dockerhub
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: contextcloud/openfaas-cloudpubsub-connector
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Publish to Dockerhub with tag
      uses: HurricanKai/Publish-Docker-Github-Action@master
      if: contains(github.ref, 'refs/tags/v')
      with:
        name: contextcloud/openfaas-cloudpubsub-connector
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tagging: true